spring.application.name=stfp-app

sftp.host=localhost
sftp.port=2222
sftp.user=usuario
sftp.password=password
sftp.private-key-path=ssh-keys/sftp_key
sftp.privateKeyPass=alex1
sftp.remoteDirectory=/uploads

